packaging_format = 2

id = "pluxml"
name = "PluXml"
description.en = "Blog or CMS storing data in XML flat files."
description.fr = "Blog ou CMS stockant ses données dans des fichiers XML plats."

version = "5.8.16~ynh1"

maintainers = ["Antoine"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.pluxml.org/"
demo = "https://demo.pluxml.org/"
admindoc = "https://wiki.pluxml.org/"
code = "https://github.com/pluxml/PluXml"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pluxml"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Default language"
    ask.fr = "Langue par défaut"
    type = "select"
    choices = ["de", "en", "es", "fr", "it", "nl", "oc", "pl", "pt", "ro", "ru"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/pluxml/PluXml/archive/refs/tags/v5.8.16.tar.gz"
        sha256 = "a716c43428793ed19f2b8346b2d6d64ac99b2ff041c1474db28481f525f196e3"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-gd php8.0-xml"
