test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.f618522e430dfcb63e1a5843535cf0da165025f3.name = "Upgrade from 5.7~ynh1"