#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

# Remove sources
sudo rm -rf /var/www/$app

# Remove nginx conf and reload nginx service
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo service nginx reload
