#!/bin/bash

app=$YNH_APP_INSTANCE_NAME
domain=$(sudo yunohost app setting $app domain)

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Remove sources
sudo rm -rf /var/www/$app

# Remove nginx conf and reload nginx service
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo service nginx reload
