#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

app=pluxml
app_path=/var/www/$app
save_path=$1

# Source YunoHost helpers
source /usr/share/yunohost/helpers

sudo cp $save_path/config.php $app_path/
sudo rm -rf $app_path/data
sudo cp -R $save_path/data $app_path/
sudo chown -R www-data: $app_path/data
